	IFND	GRAPHICS_DISPLAY_I
GRAPHICS_DISPLAY_I	=	1
MODE_640	=	$8000
PLNCNTMSK	=	$7
PLNCNTSHFT	=	12
PF2PRI		=	$40
COLORON		=	$0200
DBLPF		=	$400
HOLDNMODIFY	=	$800
INTERLACE	=	4
PFA_FINE_SCROLL	=	$F
PFB_FINE_SCROLL_SHIFT=	4
PF_FINE_SCROLL_MASK=	$F
DIW_HORIZ_POS	=	$7F
DIW_VRTCL_POS	=	$1FF
DIW_VRTCL_POS_SHIFT=	7
DFTCH_MASK	=	$FF
VPOSRLOF	=	$8000
	ENDC
